pipeline:
  # test:
  #   image: node
  #   environment:
  #     NODE_PATH: src
  #   commands:
  #     - npm install --quiet
  #     - npm run test
  #   when:
  #     branch: master
  #     event: pull_request

  code-analysis:
    # image: aosapps/drone-sonar-plugin
    # sonar_host: https://sonar.devheaven.nl
    # sonar_token: ae81df1bded95618eab67fb41693825b0e14d2db
    image: ypcloud/sonar-runner
    sources: "./source"
    secrets: [ sonar_host, sonar_login, sonar_password ]
    when:
      branch: master
      event: pull_request

  publish-staging:
    image: plugins/docker
    repo: devheavenci/task-management-service
    tags: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish-production:
    image: plugins/docker
    repo: devheavenci/task-management-service
    tags: "${DRONE_TAG##v}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  deploy-staging:
    image: quay.io/honestbee/drone-kubernetes
    namespace: staging
    deployment: task-management-deployment
    repo: devheavenci/task-management-service
    container: task-management
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      branch: master
      event: push

  deploy-production:
    image: quay.io/honestbee/drone-kubernetes
    namespace: production
    deployment: task-management-deployment
    repo: devheavenci/task-management-service
    container: task-management
    tag: "${DRONE_TAG##v}"
    secrets: [ kubernetes_server, kubernetes_token ]
    when:
      event: tag

branches: master
